### ISSUE TITLE
button labels are not properly alerted

### ISSUE THREAD

**Issue by akhilesh132** [RAM-451/practice#1]
button labels are not properly alerted

**Comment by akhilesh132** [comment]
for (let buttonNum = 1; buttonNum <= 100; buttonNum++){
      document.write("<button>"+buttonNum+"</button>");
}

**Comment by RAM-451** [comment]
for (let buttonNum = 1; buttonNum <= 5; buttonNum++){
document.write("<button>"+buttonNum+"</button>");
}

**Comment by RAM-451** [comment]
<script >
      for (let buttonNum = 1; buttonNum <= 5; buttonNum++){
document.write("<button>"+buttonNum+"</button>");
}
</script>

**Comment by RAM-451** [comment]
Chjanged jQuery to DOM
